# Generated by Django 3.1 on 2020-08-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djumanji', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='company',
            name='employee_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='picture',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.DateTimeField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_max',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary_min',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='skills',
            field=models.CharField(default='', max_length=200),
        ),
    ]
