# Generated by Django 3.1 on 2020-08-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djumanji', '0002_auto_20200805_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='published_at',
            field=models.CharField(default='', max_length=200),
        ),
    ]
